version: "3"

services:
  # Access via "http://localhost:80"
  drupal:
    image: gekal/drupal:9.4-apache
    container_name: drupal-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
    depends_on:
      - db
    volumes:
      - ./drupal/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./drupal/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
      # - ./drupal/web/sites/default:/var/www/html/web/sites/default

  db:
    image: mysql:5
    container_name: drupal-db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: drupal
      MYSQL_PASSWORD: password
    restart: always
    volumes:
      - ./drupal/db/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./drupal/db/initdb:/docker-entrypoint-initdb.d/:ro
      # 必要によって、DBのdataを外部に出す
      # - ./drupal/db/data:/var/lib/mysql
